### ISSUE TITLE
Enhancements of the MLUltrasound-Class

### ISSUE THREAD

**Issue by JanKirchhofTU** [EMS-TU-Ilmenau/fastmat#30]
### Changes to be made
* ~~Rename to BlockTwoLevelToeplitz~~
* Constructor should not load any data, but can only receive a path to the defining vectors
* The diagonalization process should not happen in the constructor but instead when befor the first projection/multiplication
* `getCols()` and `getRows()` should be overloaded with routines not using the frequency domain
* get rid of Kronecker-Products of Fourier-Matrices

### Expected gains
* World domination
* Be able to extract parts of the matrix, w\o constructing it completely in the first place
* speed-ups

### Future extensions:
* Can we extend this to N-Level?

**Comment by SebastianSemper** [comment]
Renaming was added in [https://github.com/EMS-TU-Ilmenau/fastmat/commit/ca40a577807e8a36c336bd9be81a8dce4282330f]()

**Comment by ChristophWWagner** [comment]
The Fourier-Kronecker-Product-Problem should be mitigable by using the NDFourier.

Please be aware, that the `_getCol()` and `_getRow()` need to be overloaded in order to redefine the behaviour of `getCols()` and `getRows()`.

What is meant by "should not load any data, but can only receive a path to the defining vectors"?

**Comment by SebastianSemper** [comment]
In view of recent developments, this issue is obsolete. Closing.
