### ISSUE TITLE
Memory Acess Error with fm.Blocks and fm.Sparse

### ISSUE THREAD

**Issue by JanKirchhofTU** [EMS-TU-Ilmenau/fastmat#81]
Say I have two sparse matrices and I want to construct a block matrix from those:
```python
import scipy.sparse
import fastmat as fm

a = fm.Sparse(
scipy.sparse.csr_matrix((3, 5))
)
b = fm.Sparse(
scipy.sparse.csr_matrix((3, 5))
)

# This works as expected
c = fm.Blocks([[a,b], [a,b]])
# This works as expected
d = fm.Blocks([[a,b]])
# This crashes with a Memory Access Error
e = fm.Blocks([a,b])
```
I am running
* fastmat0.2a4
* scipy1.3.3
* python 3.8.1

on a linux system.

**Comment by ChristophWWagner** [comment]
This one is a tough one as it is a good example for an "ungraceful fail" and should produce a more meaningful error message.

`Blocks` expects  a double list. However, since you can index into fastmat matrices this is what probably happens at the second level. Duck typing ftw! The problem, unfortunately, lies in deciding what not do disallow in order to get this thing cleaner without impacting duck typing magic too much.

My suggestion would be to specifically disallow `fastmat.Matrix` as second-level container.

Other suggestions?

**Comment by SebastianSemper** [comment]
Would go down the same route. The supplied list should always contain
another list, but then we should also check, if at the third level we
finally have a matrix.

**Comment by ChristophWWagner** [comment]
In e24862c such an error message, warning about broken second iteration levels in the structure passed to `Blocks.__init__()`, was added. Hope that's enough to mitigate crashes from this failure vector in the future. Closing. Feel free to reopen if problems still persist.
