### ISSUE TITLE
Error while building the doc locally

### ISSUE THREAD

**Issue by ahmadomira** [EMS-TU-Ilmenau/fastmat#88]
Running following command from fastmat root directory: 
```
python3 setup.py build_doc
```
after cythonizing 27 fastmat's objects: 
```bash
Running Sphinx v3.3.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "~/git/fastmat/doc/conf.py", line 25, in <module>
    import fastmat.version as fmv
  File "~git/fastmat/fastmat/__init__.py", line 62, in <module>
    from .Matrix import Matrix, Hermitian, Conjugate, Transpose, flags
ModuleNotFoundError: No module named 'fastmat.Matrix'
```

**OS:** MacOS Big Sur version 11.0.1
**Python:** v3.8.6
**C-compiler:** Clang 6.0 (clang-600.0.57)

**Comment by ChristophWWagner** [comment]
This reads like the python interpreter cannot load the compiled source objects but finds the header references (`__init__.py`) of the package and its submodules. That's most likely an issue on your local side, possibly caused by one of the following reasons:
 - fastmat was installed under python2 using `pip` and is now required from `python3` (for the sphinx build)
 - there are multiple instances of fastmat installed in different places (sometimes this may happen when installed with `sudo`)
 - depending on your current working directory and your default `sys.path`, the source code directory (contained in the base repository path) is higher in import priority than any of the buid directories. Since the binaries are no longer compiled next to the source, but rather being collated in a separate `build` directory, having the blank source files in some high-priority might cause this effect, too.

Please update if the problem still persists

**Comment by ChristophWWagner** [comment]
Testing with verious python (2.7, 3.5, 3.7 and 3.9) and OS versions (Debian 10, Windows 10, WSL 1 Debian 9, WSL 1 Debian 10, WSL 1 Ubuntu) did not reveal any problems so far.

Please reopen the issue if you find a reproducible setup to continue this investigation
