### ISSUE TITLE
PyPI package outdated

### ISSUE THREAD

**Issue by CBockelmann** [EMS-TU-Ilmenau/fastmat#91]
The version installed via `pip install fastmat` is `0.1.2.post1`.

However, the git repository and examples are at a higher version which is also not available as a release.

**Comment by SebastianSemper** [comment]
You can use `pip install fastmat --pre` to get version `0.2a4` as a source distribution. So you need the build dependencies so that pip is able to to compile the wheel from source.

**Comment by ChristophWWagner** [comment]
Dear @CBockelmann,

Thank you for voicing your justified demand for the release. Due to high occupancy from other projects, I am very sorry that the release 0f `0.2` has dragged on for such a long time and would like to apologize for the inconvenience, in particular since there were quite some extensions and improvements over 0.1.2 that are not (yet) reflected in an easily accessible release on pypi.

**Please be assured that we are working on resolving this situation during the upcoming month.**

In the meantime you may use the workaround of installing the package from source, either by the suggestion from SebastianSemper or by explicit specification of the latest source release on pypi: `pypi isntall fastmat==0.2a4`

Please let me know if we can help with a particular issue that you are currenty facing as a concequence of the delay.

Best regards,

Christoph

**Comment by ChristophWWagner** [comment]
Dear @CBockelmann,

the release process just completed. `fastmat´ 0.2 is now available on pypi for download.

Best regards

Christoph
